env:
  commonjs: true
  es6: true
  browser: true
  jest: true
extends: airbnb
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    ecmaVersion: 6
    jsx: true
    sourceType: module
plugins:
  - react
  - react-hooks
rules:
  brace-style: [error, 1tbs, { "allowSingleLine": true }]
  max-len:
    - error
    - 125
    - 2
    # - ignoreStrings: true
    # - ignoreTrailingComments: true
    #   ignoreRegExpLiterals: true
    #   ignorePattern: '\\s*<'
  no-unused-vars: warn
  no-plusplus: 0
  no-param-reassign: warn
  quotes:
    - error
    - single
  comma-dangle: 0
  object-curly-newline: 0
  function-paren-newline: 0
  no-tabs: 0
  indent:
    - error
    - tab
    - SwitchCase: 1
  react/jsx-indent:
    - error
    - tab
  react/jsx-indent-props:
    - error
    - tab
  no-underscore-dangle: [2, { "allowAfterThis": true }]
  arrow-parens: [error, "as-needed"]
  import/extensions: 0
  prefer-const: warn
  arrow-body-style: [error, "always"]
  react/no-unused-prop-types: 0
  react/prop-types: 0
  react/jsx-filename-extension: 0
  react/forbid-prop-types: 0
  react/jsx-pascal-case: 2
  react/no-did-mount-set-state: 0
  react/react-in-jsx-scope: 0
  jsx-a11y/href-no-hash: off
  jsx-a11y/anchor-is-valid: ["warn", { "aspects": ["invalidHref"] }] # work around
  linebreak-style: 0
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  react/jsx-one-expression-per-line: 0
settings:
  import/resolver:
    node:
      extensions:
        - .jsx
        - .js
        - .android.js
        - .ios.js
        - .json
        - .android.json
        - .ios.json
